import type { CandidateMetrics, ScoredLocation } from "./types";

export const CITY_OPTIONS = [
  { id: "ljubljana", name: "Ljubljana" },
  { id: "maribor", name: "Maribor" },
  { id: "celje", name: "Celje" },
  { id: "koper", name: "Koper" },
  { id: "kranj", name: "Kranj" },
  { id: "nova_gorica", name: "Nova Gorica" },
] as const;

export type CityId = (typeof CITY_OPTIONS)[number]["id"];
export type CityName = (typeof CITY_OPTIONS)[number]["name"];

export const CITY_NAME_BY_ID: Record<CityId, CityName> = {
  ljubljana: "Ljubljana",
  maribor: "Maribor",
  celje: "Celje",
  koper: "Koper",
  kranj: "Kranj",
  nova_gorica: "Nova Gorica",
};

export const CITY_DISTRICTS: Record<CityId, readonly string[]> = {
  ljubljana: ["Vsa območja", "Center", "Bežigrad", "Šiška", "Vič-Rudnik", "Moste-Polje"],
  maribor: ["Vsa območja", "Center", "Lent", "Tabor", "Studenci", "Tezno", "Pobrežje", "Melje"],
  celje: ["Vsa območja", "Center", "Lava", "Hudinja", "Gaberje", "Teharje", "Otok"],
  koper: ["Vsa območja", "Center", "Semedela", "Bertoki", "Olmo-Prisoje", "Šalara", "Dekani"],
  kranj: ["Vsa območja", "Center", "Planina", "Primskovo", "Stražišče", "Zlato Polje", "Britof"],
  nova_gorica: ["Vsa območja", "Center", "Solkan", "Kromberk", "Rožna Dolina", "Pristava", "Šempeter"],
};

type RawCandidate = Omit<
  ScoredLocation,
  | "reuse_score"
  | "confidence_score"
  | "breakdown"
  | "positive_reasons"
  | "warnings"
  | "summary"
  | "excluded"
  | "exclusion_reason"
>;

function poly(lat: number, lng: number, sizeM = 90): [number, number][] {
  // ~111_111 m per degree lat; lng adjusted by cos(lat)
  const dLat = sizeM / 111_111;
  const dLng = sizeM / (111_111 * Math.cos((lat * Math.PI) / 180));
  return [
    [lng - dLng, lat - dLat],
    [lng + dLng, lat - dLat],
    [lng + dLng, lat + dLat],
    [lng - dLng, lat + dLat],
    [lng - dLng, lat - dLat],
  ];
}

function loc(
  id: string,
  name: string,
  district: string,
  lat: number,
  lng: number,
  metrics: CandidateMetrics,
  program_fit: ScoredLocation["program_fit"],
  size = 90,
  municipality: CityName = "Ljubljana"
): RawCandidate {
  return {
    id,
    name,
    district,
    municipality,
    lat,
    lng,
    polygon: poly(lat, lng, size),
    metrics,
    program_fit,
  };
}

function locCity(
  municipality: CityName,
  id: string,
  name: string,
  district: string,
  lat: number,
  lng: number,
  metrics: CandidateMetrics,
  program_fit: ScoredLocation["program_fit"],
  size = 90
): RawCandidate {
  return loc(id, name, district, lat, lng, metrics, program_fit, size, municipality);
}

/** Hand-tuned candidates inspired by real Ljubljana brownfield / infill areas. */
export const RAW_CANDIDATES: RawCandidate[] = [
  loc(
    "lj-01",
    "Rog – nekdanja tovarna koles",
    "Center",
    46.0521,
    14.5135,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 180,
      distance_to_gji_m: 60,
      flood_risk_class: "low",
      land_use_category: "central",
      reuse_potential: "obsolete_building",
      area_m2: 8400,
      transit_lines_nearby: 5,
    },
    ["public_services", "small_business", "housing"],
    140
  ),
  loc(
    "lj-02",
    "Cukrarna – širše območje",
    "Center",
    46.0556,
    14.5142,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 220,
      distance_to_gji_m: 90,
      flood_risk_class: "medium",
      land_use_category: "central",
      reuse_potential: "obsolete_building",
      area_m2: 12000,
      transit_lines_nearby: 4,
    },
    ["public_services", "housing"],
    160
  ),
  loc(
    "lj-03",
    "Tobačna mesto",
    "Vič-Rudnik",
    46.0464,
    14.4904,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 150,
      distance_to_gji_m: 50,
      flood_risk_class: "none",
      land_use_category: "mixed",
      reuse_potential: "brownfield",
      area_m2: 16500,
      transit_lines_nearby: 6,
    },
    ["housing", "small_business", "public_services"],
    180
  ),
  loc(
    "lj-04",
    "Litostrojska – severni del",
    "Šiška",
    46.0735,
    14.4843,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 320,
      distance_to_gji_m: 110,
      flood_risk_class: "low",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 22000,
      transit_lines_nearby: 3,
    },
    ["small_business", "infrastructure", "housing"],
    220
  ),
  loc(
    "lj-05",
    "BTC – severovzhodna cona",
    "Moste-Polje",
    46.0688,
    14.5482,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 410,
      distance_to_gji_m: 80,
      flood_risk_class: "low",
      land_use_category: "business",
      reuse_potential: "underused_urban",
      area_m2: 18500,
      transit_lines_nearby: 3,
    },
    ["small_business", "infrastructure"],
    200
  ),
  loc(
    "lj-06",
    "Fužine – degradirani plato",
    "Moste-Polje",
    46.0539,
    14.5612,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 260,
      distance_to_gji_m: 120,
      flood_risk_class: "none",
      land_use_category: "residential",
      reuse_potential: "underused_urban",
      area_m2: 6800,
      transit_lines_nearby: 4,
    },
    ["housing", "public_services"],
    120
  ),
  loc(
    "lj-07",
    "Bežigrad – stara železniška cona",
    "Bežigrad",
    46.0731,
    14.5167,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 290,
      distance_to_gji_m: 70,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "brownfield",
      area_m2: 14200,
      transit_lines_nearby: 5,
    },
    ["housing", "small_business", "public_services"],
    170
  ),
  loc(
    "lj-08",
    "Vižmarje – urbana praznina",
    "Šiška",
    46.0931,
    14.4719,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 540,
      distance_to_gji_m: 230,
      flood_risk_class: "low",
      land_use_category: "residential",
      reuse_potential: "vacant_lot",
      area_m2: 4200,
      transit_lines_nearby: 2,
    },
    ["housing", "public_services"],
    100
  ),
  loc(
    "lj-09",
    "Zalog – industrijski rob",
    "Moste-Polje",
    46.0626,
    14.6022,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 720,
      distance_to_gji_m: 180,
      flood_risk_class: "medium",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 28000,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    240
  ),
  loc(
    "lj-10",
    "Kolinska – nekdanji obrat",
    "Bežigrad",
    46.0808,
    14.5311,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 240,
      distance_to_gji_m: 65,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "brownfield",
      area_m2: 19500,
      transit_lines_nearby: 4,
    },
    ["housing", "small_business", "public_services"],
    200
  ),
  loc(
    "lj-11",
    "Vrhovci – obrobni infill",
    "Vič-Rudnik",
    46.0367,
    14.4624,
    {
      within_settlement: false,
      edge_of_settlement: true,
      distance_to_transport_m: 880,
      distance_to_gji_m: 320,
      flood_risk_class: "medium",
      land_use_category: "residential",
      reuse_potential: "infill",
      area_m2: 5400,
      transit_lines_nearby: 1,
    },
    ["housing"],
    110
  ),
  loc(
    "lj-12",
    "Rakova jelša – poplavna ravnica",
    "Vič-Rudnik",
    46.0291,
    14.4975,
    {
      within_settlement: false,
      edge_of_settlement: true,
      distance_to_transport_m: 950,
      distance_to_gji_m: 410,
      flood_risk_class: "high",
      land_use_category: "residential",
      reuse_potential: "vacant_lot",
      area_m2: 7600,
      transit_lines_nearby: 1,
    },
    ["housing"],
    130
  ),
  loc(
    "lj-13",
    "Polje – podizkoriščeni plato",
    "Moste-Polje",
    46.0594,
    14.5836,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 470,
      distance_to_gji_m: 150,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "underused_urban",
      area_m2: 9200,
      transit_lines_nearby: 2,
    },
    ["housing", "small_business"],
    150
  ),
  loc(
    "lj-14",
    "Trnovo – mali infill",
    "Center",
    46.0413,
    14.5049,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 200,
      distance_to_gji_m: 50,
      flood_risk_class: "none",
      land_use_category: "residential",
      reuse_potential: "vacant_lot",
      area_m2: 2400,
      transit_lines_nearby: 4,
    },
    ["housing", "public_services"],
    80
  ),
  loc(
    "lj-15",
    "Stožice – obrobni servisni plato",
    "Bežigrad",
    46.0852,
    14.5234,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 380,
      distance_to_gji_m: 110,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "underused_urban",
      area_m2: 11200,
      transit_lines_nearby: 3,
    },
    ["small_business", "public_services", "infrastructure"],
    160
  ),
  loc(
    "lj-16",
    "Kodeljevo – obstoječa cona",
    "Moste-Polje",
    46.0517,
    14.5404,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 310,
      distance_to_gji_m: 95,
      flood_risk_class: "low",
      land_use_category: "central",
      reuse_potential: "underused_urban",
      area_m2: 5800,
      transit_lines_nearby: 4,
    },
    ["public_services", "housing"],
    120
  ),
  loc(
    "lj-17",
    "Vodmat – zaposlitvena cona",
    "Center",
    46.0512,
    14.5234,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 170,
      distance_to_gji_m: 55,
      flood_risk_class: "none",
      land_use_category: "central",
      reuse_potential: "obsolete_building",
      area_m2: 7400,
      transit_lines_nearby: 5,
    },
    ["public_services", "small_business", "housing"],
    140
  ),
  loc(
    "lj-18",
    "Šentvid – industrijski rob",
    "Šiška",
    46.1082,
    14.4744,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 620,
      distance_to_gji_m: 220,
      flood_risk_class: "low",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 17800,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    200
  ),
  loc(
    "lj-19",
    "Dolgi most – obrtna cona",
    "Vič-Rudnik",
    46.0395,
    14.4738,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 450,
      distance_to_gji_m: 140,
      flood_risk_class: "low",
      land_use_category: "business",
      reuse_potential: "underused_urban",
      area_m2: 13200,
      transit_lines_nearby: 3,
    },
    ["small_business", "infrastructure"],
    180
  ),
  loc(
    "lj-20",
    "Jarše – nekdanji obrat",
    "Moste-Polje",
    46.0688,
    14.5618,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 280,
      distance_to_gji_m: 100,
      flood_risk_class: "low",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 15600,
      transit_lines_nearby: 3,
    },
    ["small_business", "housing", "infrastructure"],
    180
  ),
  loc(
    "lj-21",
    "Spodnja Šiška – urban praznina",
    "Šiška",
    46.0671,
    14.4972,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 230,
      distance_to_gji_m: 70,
      flood_risk_class: "none",
      land_use_category: "mixed",
      reuse_potential: "vacant_lot",
      area_m2: 4800,
      transit_lines_nearby: 4,
    },
    ["housing", "public_services"],
    110
  ),
  loc(
    "lj-22",
    "Murgle – robni infill",
    "Vič-Rudnik",
    46.0339,
    14.4881,
    {
      within_settlement: false,
      edge_of_settlement: true,
      distance_to_transport_m: 1100,
      distance_to_gji_m: 380,
      flood_risk_class: "medium",
      land_use_category: "residential",
      reuse_potential: "infill",
      area_m2: 3800,
      transit_lines_nearby: 1,
    },
    ["housing"],
    100
  ),
  loc(
    "lj-23",
    "Kosovelova – degradirani plato",
    "Bežigrad",
    46.0764,
    14.5078,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 250,
      distance_to_gji_m: 75,
      flood_risk_class: "low",
      land_use_category: "central",
      reuse_potential: "underused_urban",
      area_m2: 6200,
      transit_lines_nearby: 5,
    },
    ["public_services", "housing", "small_business"],
    130
  ),
  loc(
    "lj-24",
    "Letališka – obrobna servisna cona",
    "Moste-Polje",
    46.0623,
    14.5703,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 510,
      distance_to_gji_m: 160,
      flood_risk_class: "low",
      land_use_category: "business",
      reuse_potential: "brownfield",
      area_m2: 21000,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    220
  ),
  locCity(
    "Maribor",
    "mb-01",
    "Lent – skladiščni pas",
    "Lent",
    46.5574,
    15.6481,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 190,
      distance_to_gji_m: 70,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "obsolete_building",
      area_m2: 7900,
      transit_lines_nearby: 4,
    },
    ["housing", "public_services", "small_business"],
    130
  ),
  locCity(
    "Maribor",
    "mb-02",
    "Melje – stari industrijski blok",
    "Melje",
    46.5655,
    15.6542,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 260,
      distance_to_gji_m: 95,
      flood_risk_class: "low",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 14600,
      transit_lines_nearby: 3,
    },
    ["small_business", "infrastructure", "housing"],
    170
  ),
  locCity(
    "Maribor",
    "mb-03",
    "Studenci – tovarniški rob",
    "Studenci",
    46.5484,
    15.6215,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 380,
      distance_to_gji_m: 130,
      flood_risk_class: "low",
      land_use_category: "industrial",
      reuse_potential: "underused_urban",
      area_m2: 18200,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    200
  ),
  locCity(
    "Maribor",
    "mb-04",
    "Tabor – urbana praznina",
    "Tabor",
    46.5489,
    15.6467,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 210,
      distance_to_gji_m: 70,
      flood_risk_class: "none",
      land_use_category: "residential",
      reuse_potential: "vacant_lot",
      area_m2: 5200,
      transit_lines_nearby: 4,
    },
    ["housing", "public_services"],
    110
  ),
  locCity(
    "Maribor",
    "mb-05",
    "Tezno – degradirana cona",
    "Tezno",
    46.5298,
    15.6587,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 460,
      distance_to_gji_m: 150,
      flood_risk_class: "medium",
      land_use_category: "business",
      reuse_potential: "brownfield",
      area_m2: 21000,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    220
  ),
  locCity(
    "Maribor",
    "mb-06",
    "Pobrežje – nekdanji obrat",
    "Pobrežje",
    46.5538,
    15.6698,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 540,
      distance_to_gji_m: 180,
      flood_risk_class: "medium",
      land_use_category: "mixed",
      reuse_potential: "underused_urban",
      area_m2: 9800,
      transit_lines_nearby: 2,
    },
    ["housing", "small_business"],
    140
  ),
  locCity(
    "Celje",
    "ce-01",
    "Center – notranji blok",
    "Center",
    46.2385,
    15.2668,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 170,
      distance_to_gji_m: 60,
      flood_risk_class: "none",
      land_use_category: "central",
      reuse_potential: "obsolete_building",
      area_m2: 6800,
      transit_lines_nearby: 4,
    },
    ["housing", "public_services", "small_business"],
    120
  ),
  locCity(
    "Celje",
    "ce-02",
    "Lava – industrijski pas",
    "Lava",
    46.2468,
    15.2552,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 300,
      distance_to_gji_m: 115,
      flood_risk_class: "low",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 15200,
      transit_lines_nearby: 3,
    },
    ["small_business", "infrastructure", "housing"],
    180
  ),
  locCity(
    "Celje",
    "ce-03",
    "Hudinja – podizkoriščena cona",
    "Hudinja",
    46.2462,
    15.2834,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 420,
      distance_to_gji_m: 170,
      flood_risk_class: "medium",
      land_use_category: "business",
      reuse_potential: "underused_urban",
      area_m2: 12400,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    165
  ),
  locCity(
    "Celje",
    "ce-04",
    "Teharje – obrobni plato",
    "Teharje",
    46.2314,
    15.2894,
    {
      within_settlement: false,
      edge_of_settlement: true,
      distance_to_transport_m: 740,
      distance_to_gji_m: 240,
      flood_risk_class: "low",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 22600,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    230
  ),
  locCity(
    "Celje",
    "ce-05",
    "Gaberje – nekdanji obrat",
    "Gaberje",
    46.2328,
    15.2701,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 260,
      distance_to_gji_m: 90,
      flood_risk_class: "none",
      land_use_category: "mixed",
      reuse_potential: "underused_urban",
      area_m2: 8400,
      transit_lines_nearby: 3,
    },
    ["housing", "small_business", "public_services"],
    130
  ),
  locCity(
    "Celje",
    "ce-06",
    "Otok – prazno zemljišče",
    "Otok",
    46.2426,
    15.2714,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 230,
      distance_to_gji_m: 85,
      flood_risk_class: "low",
      land_use_category: "residential",
      reuse_potential: "vacant_lot",
      area_m2: 4300,
      transit_lines_nearby: 3,
    },
    ["housing", "public_services"],
    100
  ),
  locCity(
    "Koper",
    "ko-01",
    "Luka Koper – servisni pas",
    "Center",
    45.5498,
    13.734,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 280,
      distance_to_gji_m: 80,
      flood_risk_class: "low",
      land_use_category: "business",
      reuse_potential: "brownfield",
      area_m2: 17000,
      transit_lines_nearby: 4,
    },
    ["small_business", "infrastructure"],
    220
  ),
  locCity(
    "Koper",
    "ko-02",
    "Semedela – obalni infill",
    "Semedela",
    45.5439,
    13.7346,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 210,
      distance_to_gji_m: 75,
      flood_risk_class: "none",
      land_use_category: "residential",
      reuse_potential: "infill",
      area_m2: 3900,
      transit_lines_nearby: 3,
    },
    ["housing", "public_services"],
    95
  ),
  locCity(
    "Koper",
    "ko-03",
    "Bertoki – logistični rob",
    "Bertoki",
    45.5382,
    13.7601,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 520,
      distance_to_gji_m: 170,
      flood_risk_class: "medium",
      land_use_category: "industrial",
      reuse_potential: "underused_urban",
      area_m2: 15600,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    190
  ),
  locCity(
    "Koper",
    "ko-04",
    "Olmo – nekdanji obrat",
    "Olmo-Prisoje",
    45.5488,
    13.7463,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 240,
      distance_to_gji_m: 90,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "obsolete_building",
      area_m2: 8200,
      transit_lines_nearby: 3,
    },
    ["housing", "public_services", "small_business"],
    120
  ),
  locCity(
    "Koper",
    "ko-05",
    "Šalara – urbana praznina",
    "Šalara",
    45.5359,
    13.7218,
    {
      within_settlement: false,
      edge_of_settlement: true,
      distance_to_transport_m: 680,
      distance_to_gji_m: 230,
      flood_risk_class: "low",
      land_use_category: "residential",
      reuse_potential: "vacant_lot",
      area_m2: 5100,
      transit_lines_nearby: 2,
    },
    ["housing"],
    120
  ),
  locCity(
    "Koper",
    "ko-06",
    "Dekani – obstoječa cona",
    "Dekani",
    45.5346,
    13.8125,
    {
      within_settlement: false,
      edge_of_settlement: true,
      distance_to_transport_m: 920,
      distance_to_gji_m: 320,
      flood_risk_class: "medium",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 24100,
      transit_lines_nearby: 1,
    },
    ["small_business", "infrastructure"],
    240
  ),
  locCity(
    "Kranj",
    "kr-01",
    "Kranj center – stari kompleks",
    "Center",
    46.2393,
    14.3568,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 180,
      distance_to_gji_m: 60,
      flood_risk_class: "none",
      land_use_category: "central",
      reuse_potential: "obsolete_building",
      area_m2: 7600,
      transit_lines_nearby: 4,
    },
    ["housing", "public_services", "small_business"],
    130
  ),
  locCity(
    "Kranj",
    "kr-02",
    "Planina – prazna parcela",
    "Planina",
    46.2341,
    14.3768,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 250,
      distance_to_gji_m: 80,
      flood_risk_class: "low",
      land_use_category: "residential",
      reuse_potential: "vacant_lot",
      area_m2: 4700,
      transit_lines_nearby: 3,
    },
    ["housing", "public_services"],
    100
  ),
  locCity(
    "Kranj",
    "kr-03",
    "Primskovo – servisna cona",
    "Primskovo",
    46.2276,
    14.3476,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 430,
      distance_to_gji_m: 150,
      flood_risk_class: "low",
      land_use_category: "business",
      reuse_potential: "underused_urban",
      area_m2: 11800,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    170
  ),
  locCity(
    "Kranj",
    "kr-04",
    "Stražišče – industrijski rob",
    "Stražišče",
    46.2486,
    14.3389,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 520,
      distance_to_gji_m: 180,
      flood_risk_class: "medium",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 19800,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    210
  ),
  locCity(
    "Kranj",
    "kr-05",
    "Zlato Polje – podizkoriščeni blok",
    "Zlato Polje",
    46.2417,
    14.3652,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 290,
      distance_to_gji_m: 100,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "underused_urban",
      area_m2: 7200,
      transit_lines_nearby: 3,
    },
    ["housing", "small_business", "public_services"],
    120
  ),
  locCity(
    "Kranj",
    "kr-06",
    "Britof – obrobni infill",
    "Britof",
    46.2696,
    14.3321,
    {
      within_settlement: false,
      edge_of_settlement: true,
      distance_to_transport_m: 860,
      distance_to_gji_m: 290,
      flood_risk_class: "medium",
      land_use_category: "residential",
      reuse_potential: "infill",
      area_m2: 4100,
      transit_lines_nearby: 1,
    },
    ["housing"],
    110
  ),
  locCity(
    "Nova Gorica",
    "ng-01",
    "Center – urbana praznina",
    "Center",
    45.9568,
    13.6492,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 160,
      distance_to_gji_m: 55,
      flood_risk_class: "none",
      land_use_category: "central",
      reuse_potential: "vacant_lot",
      area_m2: 5200,
      transit_lines_nearby: 3,
    },
    ["housing", "public_services", "small_business"],
    110
  ),
  locCity(
    "Nova Gorica",
    "ng-02",
    "Solkan – nekdanji obrat",
    "Solkan",
    45.9714,
    13.6449,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 340,
      distance_to_gji_m: 120,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "obsolete_building",
      area_m2: 8600,
      transit_lines_nearby: 3,
    },
    ["housing", "public_services", "small_business"],
    140
  ),
  locCity(
    "Nova Gorica",
    "ng-03",
    "Kromberk – poslovni rob",
    "Kromberk",
    45.9594,
    13.6742,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 470,
      distance_to_gji_m: 165,
      flood_risk_class: "low",
      land_use_category: "business",
      reuse_potential: "underused_urban",
      area_m2: 11600,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    170
  ),
  locCity(
    "Nova Gorica",
    "ng-04",
    "Rožna Dolina – obrobni infill",
    "Rožna Dolina",
    45.9516,
    13.6304,
    {
      within_settlement: false,
      edge_of_settlement: true,
      distance_to_transport_m: 720,
      distance_to_gji_m: 250,
      flood_risk_class: "medium",
      land_use_category: "residential",
      reuse_potential: "infill",
      area_m2: 3600,
      transit_lines_nearby: 1,
    },
    ["housing"],
    95
  ),
  locCity(
    "Nova Gorica",
    "ng-05",
    "Pristava – degradirani plato",
    "Pristava",
    45.9478,
    13.6566,
    {
      within_settlement: true,
      edge_of_settlement: false,
      distance_to_transport_m: 280,
      distance_to_gji_m: 95,
      flood_risk_class: "low",
      land_use_category: "mixed",
      reuse_potential: "underused_urban",
      area_m2: 6900,
      transit_lines_nearby: 3,
    },
    ["housing", "small_business", "public_services"],
    120
  ),
  locCity(
    "Nova Gorica",
    "ng-06",
    "Šempeter – podizkoriščena cona",
    "Šempeter",
    45.9297,
    13.6412,
    {
      within_settlement: true,
      edge_of_settlement: true,
      distance_to_transport_m: 430,
      distance_to_gji_m: 140,
      flood_risk_class: "low",
      land_use_category: "industrial",
      reuse_potential: "brownfield",
      area_m2: 13200,
      transit_lines_nearby: 2,
    },
    ["small_business", "infrastructure"],
    170
  ),
];

export interface CityMapConfig {
  id: CityId;
  name: CityName;
  center: [number, number];
  zoom: number;
  settlementArea: [number, number][];
  floodAreas: [number, number][][];
  transportStops: [number, number][];
}

function areaBox(lat: number, lng: number, dLat: number, dLng: number): [number, number][] {
  return [
    [lat + dLat, lng - dLng],
    [lat + dLat, lng + dLng],
    [lat - dLat, lng + dLng],
    [lat - dLat, lng - dLng],
  ];
}

export const CITY_MAP_CONFIG: Record<CityId, CityMapConfig> = {
  ljubljana: {
    id: "ljubljana",
    name: "Ljubljana",
    center: [46.0569, 14.5058],
    zoom: 13,
    settlementArea: areaBox(46.06, 14.53, 0.035, 0.08),
    floodAreas: [areaBox(46.027, 14.497, 0.009, 0.023)],
    transportStops: [
      [46.0521, 14.5055],
      [46.0569, 14.5118],
      [46.0612, 14.5145],
      [46.0688, 14.5232],
      [46.0735, 14.4843],
      [46.0464, 14.4904],
      [46.0539, 14.5612],
      [46.0808, 14.5311],
      [46.0731, 14.5167],
      [46.0517, 14.5404],
    ],
  },
  maribor: {
    id: "maribor",
    name: "Maribor",
    center: [46.5547, 15.6459],
    zoom: 13,
    settlementArea: areaBox(46.5547, 15.6459, 0.028, 0.045),
    floodAreas: [areaBox(46.553, 15.651, 0.006, 0.03)],
    transportStops: [
      [46.5562, 15.6465],
      [46.5538, 15.6522],
      [46.5601, 15.6438],
      [46.5499, 15.6411],
      [46.5486, 15.6548],
      [46.5658, 15.6496],
      [46.5384, 15.6603],
      [46.5521, 15.6712],
    ],
  },
  celje: {
    id: "celje",
    name: "Celje",
    center: [46.2389, 15.2677],
    zoom: 13,
    settlementArea: areaBox(46.239, 15.268, 0.02, 0.03),
    floodAreas: [areaBox(46.238, 15.272, 0.007, 0.022)],
    transportStops: [
      [46.2394, 15.2671],
      [46.2418, 15.2732],
      [46.2456, 15.2821],
      [46.2471, 15.2574],
      [46.2331, 15.2712],
      [46.2319, 15.2878],
      [46.2426, 15.2602],
      [46.2367, 15.2785],
    ],
  },
  koper: {
    id: "koper",
    name: "Koper",
    center: [45.5481, 13.7302],
    zoom: 13,
    settlementArea: areaBox(45.5468, 13.739, 0.017, 0.05),
    floodAreas: [areaBox(45.5418, 13.744, 0.006, 0.028)],
    transportStops: [
      [45.5485, 13.7304],
      [45.5452, 13.7349],
      [45.5497, 13.7418],
      [45.5438, 13.7467],
      [45.5387, 13.7594],
      [45.5364, 13.7222],
      [45.5534, 13.7331],
      [45.5476, 13.7528],
    ],
  },
  kranj: {
    id: "kranj",
    name: "Kranj",
    center: [46.238, 14.3556],
    zoom: 13,
    settlementArea: areaBox(46.239, 14.356, 0.025, 0.035),
    floodAreas: [areaBox(46.2475, 14.3465, 0.006, 0.02)],
    transportStops: [
      [46.2391, 14.3564],
      [46.2339, 14.3761],
      [46.2278, 14.3485],
      [46.2478, 14.3398],
      [46.2426, 14.3641],
      [46.2358, 14.3605],
      [46.2461, 14.3553],
      [46.2594, 14.3382],
    ],
  },
  nova_gorica: {
    id: "nova_gorica",
    name: "Nova Gorica",
    center: [45.9564, 13.6484],
    zoom: 13,
    settlementArea: areaBox(45.9564, 13.649, 0.022, 0.03),
    floodAreas: [areaBox(45.9665, 13.645, 0.006, 0.015)],
    transportStops: [
      [45.9567, 13.6488],
      [45.9711, 13.6451],
      [45.9592, 13.6739],
      [45.9518, 13.6313],
      [45.9482, 13.6571],
      [45.93, 13.6415],
      [45.9622, 13.6511],
      [45.9544, 13.6399],
    ],
  },
};

export const LJUBLJANA_CENTER: [number, number] = CITY_MAP_CONFIG.ljubljana.center;
export const DISTRICTS = CITY_DISTRICTS.ljubljana;
